source 'https://rubygems.org'

# common Gemfile
# will contain all gems that are the same and used in all projects
# Projects themselves should have a Gemfile in their respective support/project_name folder and immediately after the source line include: instance_eval File.read(File.dirname(__FILE__) + '/../common/Gemfile')

#gem "cucumber", "1.3.1"
#gem "rspec", "2.12.0"
#gem 'page-object'
#gem 'ruby-debug'
#gem "require_all", "1.2.1"
#gem "xpath", "0.1.4"
#gem "yml_reader", "0.2"
gem "childprocess" , "0.5.1"
gem "columnize",  "0.9.0"
gem "gherkin", "2.12.0"
gem "cucumber", "1.3.1"
gem "data_magic", "0.15.2"
gem "diff-lcs", "1.1.3"
gem "faker", "1.2.0"
gem "ffi", "1.9.0"
gem "i18n", "0.6.5"
gem "linecache", "1.3.1"
gem "multi_json", "1.7.9"
gem "nokogiri", "1.6.8"
gem "page-object", "0.9.2"
gem "page_navigation", "0.9"
gem "require_all", "1.2.1"
gem "rspec", "2.12.0"
gem "rspec-core", "2.12.2"

gem "rspec-expectations", "2.12.1"
gem "rspec-mocks", "2.12.2"
gem "ruby-debug", "0.10.6"
gem "ruby-debug-base", "0.10.6"
gem "rubyzip", "1.2.0"
gem "selenium-webdriver", "2.53.3"
gem "watir-webdriver", "0.9.1"
gem "websocket", "1.0.7"
gem "xpath", "0.1.4"
gem  "headless", "2.2.3"
gem "activerecord", "4.0.0"
gem "activerecord-jdbc-adapter", "1.3.2"
gem "activerecord-jdbcsqlite3-adapter", "1.3.2"
gem "activerecord-oracle_enhanced-adapter", "1.5.1"
=begin
gem 'selenium-webdriver', '~> 2.46'
gem "gherkin", "2.12.0"
gem "cucumber", "1.3.1"
gem "cucumber_analytics", "1.5.1"
gem "xpath", "0.1.4"
gem "yml_reader", "0.2"
gem "data_magic", "0.15.2"
gem "page-object", "0.9.2"
gem "require_all", "1.2.1"
gem "rspec-core", "2.12.2"
gem "rspec-expectations", "2.12.1"
gem "rspec-mocks", "2.12.2"
gem "rspec", "2.12.0"
gem "rake", "0.9.2.2"
gem "CFPropertyList", "2.2.1"
gem "i18n", "0.6.5"
gem "minitest", "4.7.5"
gem "multi_json", "1.7.9"
gem "atomic", "1.1.13"
gem "thread_safe", "0.1.2"
gem "tzinfo", "0.3.37"
gem "activesupport", "4.0.0", require: 'active_support/all'
gem "addressable", "2.3.5"
gem "builder", "3.1.0"
gem "gyoku", "1.1.0"
gem "akami", "1.2.0"
gem "blankslate", "2.1.2.4"
gem "ffi", "1.9.0"
gem "childprocess", "0.5.1"
gem "jschematic", "0.1.0"
gem "launchy", "2.3.0"
gem "har", "0.0.9"
gem "mime-types", "1.24"
gem "rest-client", "1.6.7"
gem "browsermob-proxy", "0.1.8"
gem "diff-lcs", "1.1.3"

gem "calabash-common", "0.0.1"
gem "parslet", "1.4.0"
gem "edn", "1.0.2"
gem "httpclient", "2.3.4.1"
gem "geocoder", "1.1.8"
gem "location-one", "0.0.10"
gem "thor", "0.18.1"
gem "run_loop", "0.2.1"
gem "rack", "1.5.2"
gem "rack-protection", "1.5.0"
gem "tilt", "1.4.1"
gem "sinatra", "1.4.3"
gem "sim_launcher", "0.4.11"
gem "slowhandcuke", "0.0.3"
gem "rack-test", "0.6.2"
gem "websocket", "1.0.7"

gem "roxml", "3.3.1"
gem "cuke_sniffer", "0.0.7"
gem "faker", "1.2.0"

gem "multi_xml", "0.5.5"
gem "httparty", "0.10.0"
gem "httpi", "2.2.3"
gem "jruby-pageant", "1.1.1"
gem "logger", "1.2.8"
gem "systemu", "2.5.2"
gem "macaddr", "1.6.1"
gem "net-http-persistent", "2.9"
gem "net-ssh", "2.6.8"
gem "nori", "2.4.0"
gem "page_navigation", "0.9"

gem "random_data", "1.6.0"

gem "wasabi", "3.3.0"
gem "savon", "2.6.0"
gem "selenium-client", "1.2.18"
gem "syntax", "1.0.0"
gem "uuid", "2.3.7"
gem "yard", "0.8.7"
gem "activerecord", "4.0.0"
gem "activerecord-jdbc-adapter", "1.3.2"
gem "activerecord-jdbcsqlite3-adapter", "1.3.2"
gem "activerecord-oracle_enhanced-adapter", "1.5.1"
gem "pry"
gem 'pry-nav'
gem "win32screenshot", "1.0.10"
gem "countries"
gem 'ruby-debug' unless ENV['RM_INFO'] # This gem is incompatible with RubyMine debugging
gem 'geokit'
gem 'memoist'
gem 'roodi', '4.0.0'

=end